Feat/MET-5362 Create API and update database for record tiers
europeana/metis-sandbox pull request #132
Opened 2023-06-28 13:12 UTC by JoanaCMS

2023-07-17 14:09 UTC, stzanakis requested changes
Seems okay, added a few comments for perhaps some small improvements.

Can we do something about the code smells introduced?

Sonar analysis is complaining about test coverage, is it something we can increase for this code, or is it because some pervious code did already not have coverage?

2023-07-17 14:09 UTC, stzanakis commented on src/test/resources/get_records_tiers_response_body.txt
> +[{"record-id":"/1/URN_NBN_SI_doc_B1HM2TA6","content-tier":"4","content-tier-before-license-correction":"4","license":"OPEN","metadata-tier":"A","metadata-tier-language":"C","metadata-tier-enabling-el
Group those files under a directory, for organization perhaps?

2023-07-18 14:06 UTC, JoanaCMS commented on src/main/java/eu/europeana/metis/sandbox/service/workflow/HarvestServiceImpl.java
> +      RecordEntity recordEntity = new RecordEntity(null, oaiHarvestData.getOaiIdentifier(), datasetId, null, null, null, null, null, null, null);
Done!

2023-07-18 16:38 UTC, JoanaCMS commented
I've tried my best to improve the code smells, and when it comes to coverage, from what I see it is because of some previous code

2023-07-19 09:25 UTC, jeortizquan reviewed
There are some `.*` imports to check.

should we consider a script for updating record table? or we just recreate the table when this goes to production.
```
ALTER TABLE record
ADD COLUMN content_tier_before_license_correction  VARCHAR(3) NULL,
ADD COLUMN metadata_tier_language                  VARCHAR(3) NULL,
ADD COLUMN metadata_tier_enabling_elements         VARCHAR(3) NULL,
ADD COLUMN metadata_tier_contextual_classes        VARCHAR(3) NULL,
ADD COLUMN license                                 VARCHAR(13) NULL;
```

2023-07-19 09:25 UTC, jeortizquan commented on src/test/java/eu/europeana/metis/sandbox/service/record/RecordServiceImplTest.java
> +import static org.mockito.Mockito.*;
just check this one has .*

2023-07-19 09:25 UTC, jeortizquan commented on src/test/java/eu/europeana/metis/sandbox/service/workflow/IndexingServiceImplTest.java
> +import eu.europeana.indexing.tiers.view.*;
check also here the import it has `*`

2023-07-19 10:59 UTC, JoanaCMS commented on src/test/java/eu/europeana/metis/sandbox/service/record/RecordServiceImplTest.java
> +import static org.mockito.Mockito.*;
Fixed

2023-07-19 11:02 UTC, JoanaCMS commented on src/test/java/eu/europeana/metis/sandbox/service/workflow/IndexingServiceImplTest.java
> +import eu.europeana.indexing.tiers.view.*;
Fixed

2023-07-19 16:23 UTC, jeortizquan approved these changes

2023-07-19 16:24 UTC, merged