MET-5085 transformation service check xslt update multiple node
europeana/metis-sandbox pull request #142
Opened 2023-11-01 16:26 UTC by jeortizquan

2023-11-02 13:03 UTC, stzanakis requested changes
I noticed that some of your later commit have a long "diff", is there something wrong with the file formats on your machine or we just happen that those files haven't been updated yet?

2023-11-02 13:03 UTC, stzanakis commented on src/main/java/eu/europeana/metis/sandbox/service/workflow/TransformationServiceImpl.java
> +        if (lockRepository.isAcquired(TransformXsltRepository.LOCK_NAME_KEY)) {
This is not really necessary here.
The xslt will be added during the first ever deployment of the application.
From then onwards there would be updates of it, so the transformation would get the one existent or the one that just replaced the older one.
So such a check here is redundant and would make records throw exceptions(rarely though), for no real reason.

2023-11-03 09:00 UTC, jeortizquan commented
> I noticed that some of your later commit have a long "diff", is there something wrong with the file formats on your machine or we just happen that those files haven't been updated yet?

true. I will check my template in my IDE probably an update reset my configuration.

2023-11-03 09:43 UTC, closed without merging

2023-11-03 09:43 UTC, stzanakis commented
As we discussed, closing this pr since the added change is not required.