Feat/met 4451 integration of problem patterns
europeana/metis-sandbox pull request #66
Opened 2022-04-21 14:57 UTC by JoanaCMS

2022-04-25 14:49 UTC, jeortizquan requested changes
There are some comments to address. In general looks fine.

2022-04-25 14:49 UTC, jeortizquan commented on src/test/java/eu/europeana/metis/sandbox/service/problempatterns/PatternAnalysisServiceImplTest.java
>      final LocalDateTime nowP6 = LocalDateTime.now();
this variable is not used.

2022-04-25 15:00 UTC, JoanaCMS commented on src/main/java/eu/europeana/metis/sandbox/controller/PatternAnalysisController.java
> +            this.datasetId = datasetProblemPatternAnalysis.getDatasetId();
Just ran the intellij formatter, hopefully now is better but I didn't see much change

2022-04-25 15:00 UTC, JoanaCMS commented on src/main/java/eu/europeana/metis/sandbox/controller/advice/ControllerErrorHandler.java
> +  @ExceptionHandler(SerializationException.class)
Just ran the formatter, hopefully now is better

2022-04-25 15:06 UTC, JoanaCMS commented on src/main/java/eu/europeana/metis/sandbox/executor/workflow/InternalValidationExecutor.java
> +    if(!hasFirstRecordArrived) {
Good thing you brought this up, this was clearly not thought through all the way...
The idea is to detect when the step validation internal is first used for a certain dataset so we can save in the database.
The way this is written right now will not execute this idea for every dataset. Need to rethink about this

2022-04-26 07:52 UTC, JoanaCMS commented on src/main/java/eu/europeana/metis/sandbox/executor/workflow/InternalValidationExecutor.java
> +    if(!hasFirstRecordArrived) {
I tried using the database, as in detecting if there was already an entry in the database, and it didn't work quite well, so I tried something different and is working now

2022-04-26 07:54 UTC, JoanaCMS commented on src/test/java/eu/europeana/metis/sandbox/service/problempatterns/PatternAnalysisServiceImplTest.java
>      final LocalDateTime nowP6 = LocalDateTime.now();
Removed

2022-04-26 07:56 UTC, JoanaCMS commented on src/main/java/eu/europeana/metis/sandbox/service/workflow/InternalValidationServiceImpl.java
> +    }
Done

2022-04-26 07:56 UTC, JoanaCMS commented on src/main/java/eu/europeana/metis/sandbox/executor/workflow/InternalValidationExecutor.java
> +  private boolean hasFirstRecordArrived = false;
this variable does not exist anymore

2022-04-26 12:19 UTC, jeortizquan approved these changes
Now the occurrences are stored in different rows. The synchronization solution should address this issue and it will be attended in MET-4470.

2022-04-26 12:19 UTC, jeortizquan commented on src/main/java/eu/europeana/metis/sandbox/service/workflow/InternalValidationServiceImpl.java
> +        Optional<ExecutionPoint> firstOccurrence = executionPointService.getExecutionPoint(datasetId, Step.VALIDATE_INTERNAL.toString());
We checked together with Joana this method. we will continue to solve the sync with MET-4470

2022-04-26 12:20 UTC, jeortizquan commented on src/main/java/eu/europeana/metis/sandbox/executor/workflow/InternalValidationExecutor.java
> +    if(!hasFirstRecordArrived) {
We discussed this topic. taking care in MET-4470.

2022-04-26 12:21 UTC, merged